---
- name: Create nginx directory on host
  tags: nginx
  become: true
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Copy nginx config to host
  tags: nginx
  become: true
  ansible.builtin.copy:
    content: "client_max_body_size 100m;"
    dest: /etc/nginx/conf.d/client_max_body_size.conf
    mode: '644'
    owner: root
    group: root

- name: Configure docker daemon logging
  become: true
  tags: docker
  ansible.builtin.copy:
    content: |
      {
        "log-driver": "journald"
      }
    dest: /etc/docker/daemon.json
    mode: '644'
    owner: root
    group: root

- name: Create nginx-proxy network
  tags: [nginx, network]
  become: true
  community.docker.docker_network:
    name: nginx-proxy
    state: present

- name: Deploy Nginx Reverse Proxy
  tags: nginx
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  community.docker.docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - name: nginx-proxy
    restart_policy: unless-stopped
    env:
      ENABLE_IPV6: "true"
      DEFAULT_HOST: "jasonernst.com"

- name: Deploy LetsEncrypt companion to the proxy
  tags: letsencrypt
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  community.docker.docker_container:
    name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: nginx-proxy
    networks:
      - name: nginx-proxy
    restart_policy: unless-stopped
    env:
      ENABLE_IPV6: "true"


- name: Create production /opt/goblog directory on host
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/prod
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Create staging /opt/goblog directory on host
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/staging
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Copy production db / files to staging on host
  tags: website
  become: true
  ansible.builtin.copy:
    src: /opt/goblog/prod/
    dest: /opt/goblog/staging
    remote_src: true
    owner: root
    group: root

- name: Copy .env to prod host
  tags: website
  become: true
  ansible.builtin.copy:
    content: |
      database=sqlite
      sqlite_db=../database.db
      client_id={{ lookup('community.general.onepassword', 'github_auth', field='username', vault='www.jasonernst.com', account_id=onepassword_account_id) }}
      client_secret={{ lookup('community.general.onepassword', 'github_auth', field='credential', vault='www.jasonernst.com', account_id=onepassword_account_id) }}
    dest: /opt/goblog/prod/.env
    mode: '644'
    owner: root
    group: root

- name: Copy .env to staging host
  tags: website
  become: true
  ansible.builtin.copy:
    content: |
      database=sqlite
      sqlite_db=../database.db
      client_id={{ lookup('community.general.onepassword', 'github_auth', field='username', vault='www.jasonernst.com', account_id=onepassword_account_id) }}
      client_secret={{ lookup('community.general.onepassword', 'github_auth', field='credential', vault='www.jasonernst.com', account_id=onepassword_account_id) }}
    dest: /opt/goblog/staging/.env
    mode: '644'
    owner: root
    group: root

- name: Create production database file if not exists
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/prod/database.db
    state: touch
    mode: '644'
    owner: root
    group: root
    modification_time: preserve
    access_time: preserve

- name: Create staging database file if not exists
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/staging/database.db
    state: touch
    mode: '644'
    owner: root
    group: root
    modification_time: preserve
    access_time: preserve

- name: Create production uploads directory
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/prod/uploads
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Create staging uploads directory
  tags: website
  become: true
  ansible.builtin.file:
    path: /opt/goblog/staging/uploads
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Deploy www.jasonernst.com
  tags: website
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  community.docker.docker_container:
    name: www.jasonernst.com
    image: compscidr/goblog:v0.1.46
    volumes:
      - /opt/goblog/prod/uploads:/go/src/github.com/compscidr/goblog/www/uploads
    mounts:
      - source: /opt/goblog/prod/database.db
        target: /go/src/github.com/compscidr/database.db
        type: bind
      - source: /opt/goblog/prod/.env
        target: /go/src/github.com/compscidr/goblog/.env
        type: bind
    networks:
      - name: nginx-proxy
    restart_policy: unless-stopped
    env:
      VIRTUAL_HOST: "www.jasonernst.com,jasonernst.com"
      VIRTUAL_PORT: "7000"
      LETSENCRYPT_HOST: "www.jasonernst.com,jasonernst.com"
      LETSENCRYPT_EMAIL: "ernstjason1@gmail.com"

- name: Deploy staging.jasonernst.com
  tags: website
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  community.docker.docker_container:
    name: staging.jasonernst.com
    image: compscidr/goblog:v0.1.46
    volumes:
      - /opt/goblog/staging/uploads:/go/src/github.com/compscidr/goblog/www/uploads
    mounts:
      - source: /opt/goblog/staging/database.db
        target: /go/src/github.com/compscidr/database.db
        type: bind
      - source: /opt/goblog/staging/.env
        target: /go/src/github.com/compscidr/goblog/.env
        type: bind
    networks:
      - name: nginx-proxy
    restart_policy: unless-stopped
    env:
      VIRTUAL_HOST: "staging.jasonernst.com"
      VIRTUAL_PORT: "7000"
      LETSENCRYPT_HOST: "staging.jasonernst.com"
      LETSENCRYPT_EMAIL: "ernstjason1@gmail.com"

# MySQL moved to media_server role (used by Ombi on NAS)
